name: Terraform CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    name: Terraform Format and validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./Monitoring
      
    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: ./Monitoring

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./Monitoring
